- name: List all repos on the REST API
  hosts: backupserver
  tasks:
    - name: Call the REST API
      ansible.builtin.include_role:
        name: rest-api
      vars:
        rest_api_fact_name: "borgwarehouse_repos"
    - name: Debug URLs
      ansible.builtin.debug:
        msg: "{{ borgwarehouse_repos.json | community.general.json_query('repoList[*].alias') }}"
  vars:
    rest_api_url: "http://{{ backupserver_hostname }}:{{ port_borgwarehouse }}"
    rest_api_endpoint: "/api/v1/repositories"
    rest_api_method: "GET"
    rest_api_headers:
      Authorization: "Bearer {{ borgwarehouse_api_key }}"
- name: Get SSH public-private key pairs
  hosts: linux
  roles:
    - ssh-keys
- name: Register in new repositories
  hosts: backupserver
  tasks:
    - name: Call the REST API
      ansible.builtin.include_role:
        name: rest-api
      when: not (borgwarehouse_repos.json.repoList | selectattr('alias', 'contains', hostvars[item].id))
      loop: "{{ groups['backupclient'] }}"
      vars:
        rest_api_data:
          alias: "{{ hostvars[item].id }}"
          alert: "{{ hostvars[item].borgwarehouse_alert | default(604800) }}"   # 7 days
          sshPublicKey: "{{ hostvars[item].ssh_public_key | trim }}"
          storageSize: "{{ hostvars[item].borgwarehouse_storage_size | default(10) }}"   # 10 GB
  vars:
    rest_api_url: "http://{{ backupserver_hostname }}:{{ port_borgwarehouse }}"
    rest_api_endpoint: "/api/v1/repositories"
    rest_api_method: "POST"
    rest_api_headers:
      Authorization: "Bearer {{ borgwarehouse_api_key }}"
    rest_api_body_format: json
- name: List all repos on the REST API
  hosts: backupserver
  tasks:
    - name: Call the REST API
      ansible.builtin.include_role:
        name: rest-api
      vars:
        rest_api_fact_name: "borgwarehouse_repos"
    - name: Debug URLs
      ansible.builtin.debug:
        msg: "{{ borgwarehouse_repos.json | community.general.json_query('repoList[*].alias') }}"
  vars:
    rest_api_url: "http://{{ backupserver_hostname }}:{{ port_borgwarehouse }}"
    rest_api_endpoint: "/api/v1/repositories"
    rest_api_method: "GET"
    rest_api_headers:
      Authorization: "Bearer {{ borgwarehouse_api_key }}"
