rest_api_body_format: form-urlencoded
rest_api_data: {}
rest_api_headers: {}
rest_api_method: GET
rest_api_status_codes: [200, 201, 202, 204]
rest_api_url: "{{ undef(hint='You must specify the REST API URL') }}"
