docker_compose_create_dirs: []
docker_compose_extra_volumes: []
docker_compose_files_owner: "{{ ansible_user }}"
docker_compose_files_group: "{{ ansible_user }}"
docker_compose_ipv6: false
docker_compose_projectname: "{{ undef(hint='You must specify the docker compose project name') }}"
docker_compose_source_basepath: "{{ playbook_dir }}"
docker_compose_rootdir: "{{ ansible_user_dir }}/docker-compose"
docker_compose_static_files_copy: []
docker_compose_template_files_copy: []
docker_socket_path: /var/run/docker.sock
docker_lib_path: /var/lib/docker
docker_uid: 1000
docker_gid: 1000

is_slave_mount_allowed: true

requested_image_version: {}
