- name: Delete smartctl
  hosts: "{{ groups['smart'] | intersect(groups['docker']) }}"
  roles:
    - docker-compose-remove
  vars:
    docker_compose_projectname: smartctl
- name: Delete smartctl as a service
  hosts: "{{ groups['smart'] | difference(groups['docker']) }}"
  roles:
    - binary-remove
  vars:
    bin_filename: smartctl
    service_name: smartctl-exporter
