- name: Deploy alloy as docker
  hosts: "{{ groups['docker'] | difference(groups['external']) }}"
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: alloy
    requested_image_version:
      alloy: "1.9.2"
    docker_compose_create_dirs:
      - name: config
      - name: data
    docker_compose_template_files_copy:
      - name: config/config.alloy
