- name: Deploy APP_NAME as docker
  hosts: XXX
  roles:
    - docker-compose
  vars_files:
    - defaults.yaml
  vars:
    docker_compose_projectname: APP_NAME
    requested_image_version:
      APP_NAME: "IMAGE_VERSION"
    docker_compose_create_dirs:
      - name: config
      - name: data
    docker_compose_template_files_copy:
      - name: XXX
