- name: Put a embyignore files in place
  hosts: omv
  tasks:
    - ansible.builtin.copy:
        dest: "{{ item.destination }}/.embyignore"
        content: "{{ item.content }}"
        mode: 0644
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop: "{{ emby_embyignores }}"
      loop_control:
        label: "{{ item.destination }}"
      when: emby_embyignores is defined
