apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    version: 28.26.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: redis
    version: 17.13.7
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
    alias: ""
    tags: []
    import-values: []
name: patchmon
type: application
version: 1.0.0
