# - name: Debug headers
#   ansible.builtin.debug:
#     msg: "{{ rest_api_headers }}"
# - name: Debug body
#   ansible.builtin.debug:
#     msg: "{{ rest_api_data }}"
- name: Call REST API with required parameters
  ansible.builtin.uri:
    url: "{{ rest_api_url }}{{ rest_api_endpoint }}"
    method: "{{ rest_api_method }}"
    headers: "{{ rest_api_headers }}"
    body: "{{ rest_api_data }}"
    body_format: "{{ rest_api_body_format }}"
    return_content: true
    validate_certs: false
    status_code: "{{ rest_api_status_codes }}"
  register: rest_api_response
  check_mode: "{{ rest_api_method != 'GET' }}"
- name: Set the result in a fact
  ansible.builtin.set_fact:
    "{{ rest_api_fact_name | default('rest_api_response') }}": "{{ rest_api_response }}"
# - name: Debug response
#   ansible.builtin.debug:
#     msg: "{{ rest_api_response }}"
